use FormulaOneAnalysis

execute dbo.NullCleanup 'CircuitsTypeAnalysis'
execute dbo.NullCleanup 'ConstructorResultsTypeAnalysis'
execute dbo.NullCleanup 'ConstructorStandingsTypeAnalysis'
execute dbo.NullCleanup 'ConstructorsTypeAnalysis'
execute dbo.NullCleanup 'DriverStandingsTypeAnalysis'
execute dbo.NullCleanup 'DriverTypeAnalysis'
execute dbo.NullCleanup 'LapTimesTypeAnalysis'
execute dbo.NullCleanup 'PitStopsTypeAnalysis'
execute dbo.NullCleanup 'QualifyingTypeAnalysis'
execute dbo.NullCleanup 'RacesTypeAnalysis'
execute dbo.NullCleanup 'ResultsTypeAnalysis'
execute dbo.NullCleanup 'SeasonsTypeAnalysis'
execute dbo.NullCleanup 'StatusTypeAnalysis'

execute dbo.RemoveDoubleQuotes 'CircuitsTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'ConstructorResultsTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'ConstructorStandingsTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'ConstructorsTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'DriverStandingsTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'DriverTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'LapTimesTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'PitStopsTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'QualifyingTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'RacesTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'ResultsTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'SeasonsTypeAnalysis'
execute dbo.RemoveDoubleQuotes 'StatusTypeAnalysis'